name: gvisor
summary: a Container Runtime Sandbox.
description: gVisor is a user-space kernel, written in Go, that implements a substantial portion of the Linux system surface.
  
adopt-info: gvisor

grade: stable
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  gvisor:
    command: bin/gvisor
    plugs:
      - home
      - network
      - removable-media

parts:
  gvisor:
plugin: nil
    source: https://github.com/google/gvisor.git
    source-type: git
    override-pull: |
     git clone https://github.com/google/gvisor.git src/github.com/google/gvisor
       cd src/github.com/google/gvisor
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/google/gvisor
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/google/gvisor/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/google/gvisor/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/gvisor
    build-snaps:
      - go
    build-packages:
      - git
      - sed
